server:
    port: 8081
    error:
        include-message: always
        include-binding-errors: always

spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/employeemanager
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true

    mail:
        host: localhost
        port: 1025
        username: hello
        password: hello

        properties:
            mail:
                smtp:
                    ssl:
                        trust: "*"
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

# DB Configuration
#    spring.datasource.url = jdbc:mysql://localhost:3306/employeemanager?allowPublicKeyRetrieval=true&useSSL=false
#    spring.datasource.username= root
#    spring.datasource.password= root
#    spring.jpa.show-sql= true
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#
#    server.port = 8081
















